name: Deploy Azure Function (Node.js) using Azure CLI

on:
  push:
    branches:
      - main # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # Remove if not needed

      - name: Archive the Function App Code
        run: zip -r functionapp.zip .

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App using Azure CLI
        run: |
          az functionapp deployment source config-zip \
            --resource-group ZenPOC \
            --name charanazclifunctionapp \
            --src functionapp.zip
